name: CI
on:
    pull_request:
        branches: main

jobs:
    validate:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: ["18.x", "20.x", "22.x"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run validate
            - run: npm run build
    # dry-run:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - name: Checkout
    #         uses: actions/checkout@v4
    #       - name: Setup node
    #         uses: actions/setup-node@v3
    #       - run: npm ci
    #       - name: Build
    #         run: npm run build
    #       - name: Release
    #         env:
    #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #         run: unset GITHUB_ACTIONS && npm run release -- --dry-run --no-ci
